# Generated by Django 5.2.7 on 2025-10-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(default='profil/defaut.jpeg', upload_to='profil/'),
        ),
    ]
